### PR TITLE
added four characters

### PR DESCRIPTION
**Pull request by mohittk**
hey there!
I added 4 characters to characters.json namely, ginnie, mcgonall, dumbledore and neville.
Finding more useful things to be added.

### CODE REVIEW

**Comment by YeffyCodeGit** [comment]
Hey there! Thanks for contributing.

So most of the data seems in order, but where did you find the wood type of Dumbledore's first wand? I know the second one is the Elder Wand, but it's never stated in any of the books, movies or anywhere else what Dumbledores wand was made of.

**Comment by mohittk** [comment]
> Hey there! Thanks for contributing.
> 
> So most of the data seems in order, but where did you find the wood type of Dumbledore's first wand? I know the second one is the Elder Wand, but it's never stated in any of the books, movies or anywhere else what Dumbledores wand was made of.

Source: https://harrypotter.fandom.com/wiki/Main_Page

**Comment by mohittk** [comment]
> Hey there! Thanks for contributing.
> 
> So most of the data seems in order, but where did you find the wood type of Dumbledore's first wand? I know the second one is the Elder Wand, but it's never stated in any of the books, movies or anywhere else what Dumbledores wand was made of.

image

**Comment by YeffyCodeGit** [comment]
> > Hey there! Thanks for contributing.
> > So most of the data seems in order, but where did you find the wood type of Dumbledore's first wand? I know the second one is the Elder Wand, but it's never stated in any of the books, movies or anywhere else what Dumbledores wand was made of.
> 
> image

For the API, I only want to keep information that is proved true. For example, it's said that Draco's patronous is a dragon, but since it's never been proven, I left it null in the json. I think it would be better you keep the fields that arent known/arent proven as null.

**Comment by mohittk** [comment]
> > > Hey there! Thanks for contributing.
> > > So most of the data seems in order, but where did you find the wood type of Dumbledore's first wand? I know the second one is the Elder Wand, but it's never stated in any of the books, movies or anywhere else what Dumbledores wand was made of.
> > 
> > 
> > image
> 
> For the API, I only want to keep information that is proved true. For example, it's said that Draco's patronous is a dragon, but since it's never been proven, I left it null in the json. I think it would be better you keep the fields that arent known/arent proven as null.

Okay! no worries, I'll remove that information.

**Comment by YeffyCodeGit** [comment]
Alright, thanks alot!

**Pull request merged**
